name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15-intel, macos-14]
        python-version: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Install GDAL (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
        if: runner.os == 'Linux'

      - name: Install GDAL (macOS)
        run: brew install gdal
        if: runner.os == 'macOS'

      - name: Install GDAL (Windows)
        run: choco install gdal
        if: runner.os == 'Windows'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Build
        run: uv sync --locked --all-extras --dev

      - name: Test
        run: env TERM=dumb TTY_INTERACTIVE=0 uv run cram tests -v
